spring:
  datasource:
    password: ${RDS_PASSWORD}
    url: user-service.cd2hwitlzmny.eu-west-1.rds.amazonaws.com
    username: postgres
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
