spring:
  datasource:
    password: ${PSQL_CI_PASSWORD}
    url: jdbc:postgresql://user-service.cd2hwitlzmny.eu-west-1.rds.amazonaws.com:5432/user-service
    username: ${PSQL_CI_USERNAME}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true