on: push
name: User Service Workflow
jobs:


#
# Initial build job, run tests
#
  Build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: registration
        ports:
          - 5432:5432
        options:
               --health-cmd pg_isready
               --health-interval 10s
               --health-timeout 5s
               --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Application Tests
        run: docker run -p 1080:1080 -p 1025:1025 maildev/maildev ; mvn --batch-mode -Dmaven.test.failure.ignore=true test;


      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
