on: push
name: ...
jobs:


  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: install psql
        run: sudo apt install postgresql

      - name: start psql
        run: sudo service postgresql start


      - name: create db
        run: psql registration

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true





#  build-job:
#    name: build project
#    runs-on: ubuntu-latest



 #       options:
               #    --health-cmd pg_isready
               #    --health-interval 10s
               #    --health-timeout 5s
               #    --health-retries 5
#    steps:
      #- run: sudo service postgresql start
      #- run: psql registration
#     - run: mvn exec:java "-Dexec.mainClass=com.userservice.Application"
#        name: Start application


#    services:
#      postgres:
#        image: postgres:12.2
#        env:
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_USER: postgres
#        ports:
#          - 5432:5432
#options:
#  --health-cmd pg_isready
#  --health-interval 10s
#  --health-timeout 5s
#  --health-retries 5